using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Economy
{
    static class GetItem
    {
        public static string GetItemIdFromName(string name)
        {
            switch (name)
            {
                case "Fancy_Shades":
                    return "0";
                case "Civilian_NVG":
                    return "1";
                case "Stetson":
                    return "2";
                case "Construction_Helmet":
                    return "3";
                case "Fire_Helmet":
                    return "4";
                case "Police_Cap":
                    return "5";
                case "Desert_Helmet":
                    return "7";
                case "Forest_Helmet":
                    return "8";
                case "Dixie_Hat":
                    return "9";
                case "Bandana":
                    return "10"; 
                case "Ghillie_Hood":
                    return "11";
                case "Ninja_Hood":
                    return "12";
                case "Farmer_Hat":
                    return "13";
                case "Chef_Hat":
                    return "14";
                case "Beret":
                    return "15";
                case "Ushanka":
                    return "16";
                case "Military_NVG":
                    return "17";
                case "White_Hat":
                    return "18";
                case "Miner_Helmet":
                    return "19";
                case "Knapsack":
                    return "2000";
                case "Schoolbag":
                    return "2001";
                case "Travelpack":
                    return "2002";
                case "Coyotepack":
                    return "2003";
                case "Rucksack":
                    return "2004";
                case "Alicepack":
                    return "2005";
                case "Animalpack":
                    return "2006";
                case "Civilia_Armor":
                    return "3000";
                case "Desert_Armor":
                    return "3001";
                case "Forest_Armor":
                    return "3002";
                case "Police_Armor":
                    return "3003";
                case "Poncho":
                    return "3004";
                case "Magick_Cloak":
                    return "3005";
                case "Fancy_Suit":
                    return "4000";
                case "RCMP_Uniform":
                    return "4001";
                case "Police_Uniform":
                        return "4002";
                case "Army_Fatigues":
                        return "4003";
                case "Fireperson_Top":
                        return "4005";
                case "Construction_Vest":
                        return "4007";
                case "Doctor_Coat":
                        return "4008";
                case "Orange_Hoodie":
                        return "4009";
                case "Pink_Shirt":
                        return "4010";
                case "Boring_Suit":
                        return "4011";
                case "Blue_Sweatervest":
                        return "4012";
                case "Jumper_Top":
                        return "4013";
                case "Grocer_Top":
                        return "4014";
                case "Sailor _Fatigues":
                        return "4015";
                case "Animal_Shirt":
                        return "4016";
                case "Ghillie_Top":
                        return "4017";
                case "Ninja_Top":
                        return "4018";
                case "Plaid_Shirt":
                        return "4019";
                case "Chef_Shirt":
                        return "4020";
                case "Fancy_Jeans":
                        return "5000";
                case "Fireperson_Pants":
                        return "5005";
                case "Work_Jeans":
                        return "5007";
                case "Doctor_Pants":
                        return "5008";
                case "Grey_Pants":
                        return "5009";
                case "Khaki_Pants":
                        return "5010";
                case "Boring_Pants":
                        return "5011";
                case "Brown_Pants":
                        return "5012";
                case "Jumper_Bottom":
                        return "5013";
                case "Grocer_Bottom":
                        return "5014";
                    case "Animal_Pants":
                        return "5016";
                case "Ghillie_Bottom":
                        return "5017";
                case "Ninja_Bottom":
                        return "5018";
                case "Lumberjack_Pants":
                        return "5019";
                case "Chef_Pants":
                        return "5020";
                case "Swissgewehr":
                        return "7000";
                case "Colt":
                        return "7001";
                case "Double_Barrel":
                        return "7002";
                case "Mosen":
                        return "7003";
                case "Longbow":
                        return "7004";
                case "Novuh":
                        return "7005";
                case "Berette":
                        return "7006";
                case "Crossbow":
                        return "7007";
                case "Maplestrike":
                        return "7008";
                case "Zubeknakov":
                        return "7009";
                case "Magnum":
                        return "7010";
                case "Timberwolf":
                        return "7011";
                case "Uzy":
                        return "7012";
                case "Matamorez":
                        return "7013";
                case "Compound_Bow":
                        return "7014";
                case "Outfield":
                        return "7015";
                case "Lever_Action":
                        return "7016";
                case "Proninety":
                        return "7017";
                case "Desert_Falcon":
                        return "7018";
                case "Axe":
                        return "8000";
                case "Handlamp":
                        return "8001";
                case "Pick":
                        return "8002";
                case "Kitchen_Knife":
                        return "8003";
                case "Hammer":
                        return "8004";
                case "Frying_Pan":
                        return "8005";
                case "Baseball_Bat":
                        return "8006";
                case "Police_Baton":
                        return "8007";
                case "Torch":
                        return "8008";
                case "Fireaxe":
                        return "8009";
                case "Crowbar":
                        return "8010";
                case "Pocketknife":
                        return "8011";
                case "Butcher_Knife":
                        return "8012";
                case "Sledgehammer":
                        return "8013";
                case "Golf_Club":
                        return "8014";
                case "Katana":
                        return "8015";
                case "Machete":
                        return "8016";
                case "Spike":
                        return "8017";
                case "Branch":
                        return "8018";
                case "Handsaw":
                        return "8019";
                case "Red_Dot_Sight":
                        return "9000";
                case "Open_Circle_Rail":
                        return "9001";
                case "12x_Zoom_Scope":
                        return "9002";
                case "Holographic_Sight":
                        return "9003";
                case "6x_Zoom_Scope":
                        return "9004";
                case "Half_Circle_Rail":
                        return "9005";
                case "Full_Circle_Rail":
                        return "9006";
                case "Dual_Component_Rail":
                        return "9007";
                case "Planar_Track_Rail":
                        return "9008";
                case "20x_Zoom_Scope":
                        return "9009";
                case "Zoomomatic":
                        return "9010";
                case "Point_Circle_Sight":
                        return "9011";
                case "7x_Zoom_Scope":
                        return "9012";
                case "Dual_Point_Rail":
                        return "9013";
                case "NATO_Magazine":
                        return "10000";
                case "NATO_Drum":
                        return "10001";
                case "Swift_Magazine":
                        return "10002";
                case "Bonjour_Clip":
                        return "10003";
                case "Lebel_Magazine":
                        return "10004";
                case "NATO_Tracer":
                        return "10005";
                case "Savage_Magazine":
                        return "10006";
                case "Savage_Drum":
                        return "10007";
                case "Winchestre_Clip":
                        return "10008";
                case "Lapua_Magazine":
                        return "10009";
                case "Lapua_Tracer":
                        return "10010";
                case "Yuri_Magazine":
                        return "10011";
                case "Xtrmin_Magazine":
                        return "10012";
                case "PDW_Magazine":
                        return "10013";
                case "Vertical_Grip":
                        return "11000";
                case "Angled_Grip":
                        return "11001";
                case "Tactical_Laser":
                        return "11002";
                case "Tactical_Light":
                        return "11003";
                case "Bipod":
                        return "11004";
                case "Bayonet":
                        return "11005";
                case "Suppressor":
                        return "12000";
                case "Flash_Hider":
                        return "12001";
                case "Muffler":
                        return "12002";
                case "Medkit":
                        return "13000";
                case "Rag":
                        return "13001";
                case "Splint":
                        return "13002";
                case "Vitamins":
                        return "13003";
                case "Antibiotics":
                        return "13004";
                case "Painkillers":
                        return "13005";
                case "Dressing":
                        return "13006";
                case "Blood_Bag":
                        return "13007";
                case "Bandage":
                        return "13008";
                case "Adrenaline":
                        return "13009";
                case "Morphine":
                        return "13010";
                case "Crushed_Red_Berries":
                        return "13011";
                case "Crushed_Blue_Berries":
                        return "13012";
                case "Crushed_Pink_Berries":
                        return "13013";
                case "Crushed_Pale_Berries":
                        return "13014";
                case "Crushed_Green_Berries":
                        return "13015";
                case "Crushed_Purple_Berries":
                        return "13016";
                case "Purification_Tablets":
                        return "13017";
                case "Vaccine":
                        return "13018";
                case "Canned_Beans":
                        return "14000";
                case "Granola_Bar":
                        return "14001";
                case "Fresh_Carrot":
                        return "14002";
                case "Moldy_Carrot":
                        return "14003";
                case "Fresh_Tomato":
                        return "14004";
                case "Moldy_Tomato":
                        return "14005";
                case "Fresh_Corn":
                        return "14006";
                case "Moldy_Corn":
                        return "14007";
                case "Fresh_Cabbage":
                        return "14008";
                case "Moldy_Cabbage":
                        return "14009";
                case "Fresh_Potato":
                        return "14010";
                case "Moldy_Potato":
                        return "14011";
                case "Cooked_Venison":
                        return "14012";
                case "Raw_Venison":
                        return "14013";
                case "Canned_Soup":
                        return "14014";
                case "Canned_Chili":
                        return "14015";
                case "Canned_Vegetables":
                        return "14016";
                case "Canned_Pasta":
                        return "14017";
                case "Canned_Ham":
                        return "14018";
                case "Canned_Tuna":
                        return "14019";
                case "Candy_Bar":
                        return "14020";
                case "Chocolate_Bar":
                        return "14021";
                case "MRE":
                        return "14022";
                case "Potato_Chips":
                        return "14023";
                case "Bran_Cereal":
                        return "14024";
                case "Red_Berries":
                        return "14025";
                case "Blue_Berries":
                        return "14026";
                case "Pink_Berries":
                        return "14027";
                case "Pale_Berries":
                        return "14028";
                case "Green_Berries":
                        return "14029";
                case "Purple_Berries":
                        return "14030";
                case "Coconut":
                        return "14031";
                case "Cooked_Bacon":
                        return "14032";
                case "Raw_Bacon":
                        return "14033";
                case "Bottled_Water":
                        return "15000";
                case "Canned_Cola":
                        return "15001";
                case "Apple_Juice_Box":
                        return "15002";
                case "Large_Bottled_Water":
                        return "15003";
                case "Energy_Drink":
                        return "15004";
                case "Moldy_Milk":
                        return "15005";
                case "Moldy_Orange_Juice":
                        return "15006";
                case "Moldy_Bottled_Water":
                        return "15007";
                case "Milk":
                        return "15008";
                case "Orange_Juice":
                        return "15009";
                case "Wooden_Shield":
                        return "16000";
                case "Metal_Door":
                        return "16001";
                case "Worklight":
                        return "16002";
                case "Caltrop":
                        return "16003";
                case "Barbed_Wire":
                        return "16004";
                case "Wooden_Spike_Trap":
                        return "16005";
                case "Snare":
                        return "16006";
                case "Generator":
                        return "16007";
                case "Note":
                        return "16008";
                case "Electric_Trap":
                        return "16009";
                case "Sandbags":
                        return "16010";
                case "Sleeping_Bag":
                        return "16011";
                case "Cot":
                        return "16012";
                case "Campfire":
                        return "16013";
                case "Metal_Shutter":
                        return "16014";
                case "MOAB":
                        return "16015";
                case "Tripmine":
                        return "16016";
                case "Landmine":
                        return "16017";
                case "Metal_Shield":
                        return "16018";
                case "Wooden_Crate":
                        return "16019";
                case "Barbed_Fence":
                        return "16020";
                case "Electric_Fence":
                        return "16021";
                case "Wooden_Door":
                        return "16022";
                case "Metal_Locker":
                        return "16023";
                case "Wooden_Shutter":
                        return "16024";
                case "Wooden_Chest":
                        return "16025";
                case "Brazier":
                        return "16026";
                case "Wooden_Gate":
                        return "16027";
                case "Metal_Gate":
                        return "16028";
                case "Wooden_Foundation":
                        return "17000";
                case "Wooden_Wall":
                        return "17001";
                case "Wooden_Doorway":
                        return "17002";
                case "Wooden_Pillar":
                        return "17003";
                case "Wooden_Platform":
                        return "17004";
                case "Wooden_Ramp":
                        return "17005";
                case "Greenhouse_Foundation":
                        return "17006";
                case "Greenhouse_Platform":
                        return "17007";
                case "Wooden_Hole":
                        return "17008";
                case "Wooden_Ladder":
                        return "17009";
                case "Wooden_Window":
                        return "17010";
                case "Wooden_Post":
                        return "17011";
                case "Wooden_Rampart":
                        return "17012";
                case "Stone_Rampart":
                        return "17013";
                case "Stone_Post":
                        return "17014";
                case "Stone_Wall":
                        return "17015";
                case "Stone_Doorway":
                        return "17016";
                case "Stone_Window":
                        return "17017";
                case "Stone_Pillar":
                        return "17018";
                case "Dock_Foundation":
                        return "17019";
                case "Wooden_Garage":
                        return "17020";
                case "Stone_Garage":
                        return "17021";
                case "Board":
                        return "18000";
                case "Nails":
                        return "18001";
                case "Bolts":
                        return "18002";
                case "Log":
                        return "18003";
                case "Stick":
                        return "18004";
                case "Animal_Pelt":
                        return "18005";
                case "Rope":
                        return "18006";
                case "Wire":
                        return "18007";
                case "Scrap_Metal":
                        return "18008";
                case "Cloth":
                        return "18009";
                case "Duct_Tape":
                        return "18010";
                case "Can":
                        return "18011";
                case "Raw_Explosives":
                        return "18012";
                case "Civilian_Bullets":
                        return "18013";
                case "Military_Bullets":
                        return "18014";
                case "Stone":
                        return "18015";
                case "Tracer_Bullets":
                        return "18016";
                case "Batteries":
                        return "18017";
                case "Wooden_Spike":
                        return "18018";
                case "Rocks":
                        return "18019";
                case "Shells":
                        return "18020";
                case "Wooden_Plate":
                        return "19000";
                case "Wooden_Support":
                        return "19001";
                case "Wooden_Frame":
                        return "19002";
                case "Wooden_Cross":
                        return "19003";
                case "Stone_Plate":
                        return "19004";
                case "Stone_Support":
                        return "19005";
                case "Stone_Frame":
                        return "19006";
                case "Stone_Cross":
                        return "19007";
                case "Gas_Can":
                        return "20000";
                case "Car_Jack":
                        return "20001";
                case "Blowtorch":
                        return "21000";
                case "Chainsaw":
                        return "21001";
                case "Carrot_Seed":
                        return "22000";
                case "Tomato_Seed":
                        return "22001";
                case "Corn_Seed":
                        return "22002";
                case "Cabbage_Seed":
                        return "22003";
                case "Potato_Seed":
                        return "22004";
                case "Road_Flare":
                        return "23000";
                case "Red_Chemlight":
                        return "23001";
                case "Blue_Chemlight":
                        return "23002";
                case "Yellow_Chemlight":
                        return "23003";
                case "Green_Chemlight":
                        return "23004";
                case "Orange_Chemlight":
                        return "23005";
                case "Purple_Chemlight":
                        return "23006";
                case "Frag_Grenade":
                        return "23007";
                case "Smoke_Grenade":
                        return "23008";
                case "Binoculars":
                        return "24000";
                case "Buckshot":
                        return "25000";
                case "Arrow":
                        return "25001";
                case "Slug":
                        return "25002";
                case "Canteen":
                        return "26000";
                case "Fertilizer":
                        return "27000";
                case "PEI_Map":
                        return "28000";
            }
            return String.Empty;
        }
    }
}
